export const ADD_GAME_REQUEST = 'ADD_GAME_REQUEST';
export const ADD_GAME_SUCCESS = 'ADD_GAME_SUCCESS';
export const ADD_GAME_ERROR = 'ADD_GAME_ERROR';

export const END_GAME_REQUEST = 'END_GAME_REQUEST';
export const END_GAME_ERROR = 'END_GAME_ERROR';
export const END_GAME_SUCCESS = 'END_GAME_SUCCESS';

export const SPECTATE_GAME_REQUEST = 'SPECTATE_GAME_REQUEST';
export const SPECTATE_GAME_ERROR = 'SPECTATE_GAME_ERROR';
export const SPECTATE_GAME_SUCCESS = 'SPECTATE_GAME_SUCCESS';

export const JOIN_GAME_REQUEST = 'SPECTATE_GAME_REQUEST';
export const JOIN_GAME_ERROR = 'SPECTATE_GAME_ERROR';
export const JOIN_GAME_SUCCESS = 'SPECTATE_GAME_SUCCESS';

export const GET_AVAILABLE_GAMES_REQUEST = 'GET_AVAILABLE_GAMES_REQUEST'
export const GET_AVAILABLE_GAMES_ERROR = 'GET_AVAILABLE_GAMEs_ERROR'
export const GET_AVAILABLE_GAMES_SUCCESS = 'GET_AVAILABLE_GAMES_SUCCESS'
